### ISSUE TITLE
Build not compatible with .NET 7

### ISSUE THREAD

**Issue by richardtallent-erm** [EULexNET/EULex.NET#10]
.NET 7 has now been released, and it is only compatible with libraries compiled for .NET Standard 2.0+, .NET 6+, or .NET Framework 4.6.2+. This library only targets .NET 5, so it is now incompatible. Details:

https://learn.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/7.0/old-framework-support

I was able to upgrade the library to target .NET Standard 2.0, which is still compatible with .NET 5 and 6 (and various framework versions) but extends that support to .NET 7 as well, I'll send a PR.

**Comment by bl8** [comment]
PR merged, so closing this.
Thanks !
