### ISSUE TITLE
A fault was returned by the server exception

### ISSUE THREAD

**Issue by mirhat** [EULexNET/EULex.NET#4]
I am getting exception

> EULex.SimpleSOAPClient.FaultException: 'A fault was returned by the server'

The code is as follows
```
using (var client = new Client(username, password))
            {

                var request = new SearchRequest
                {
                    ExpertQuery = "TI ~ privacy",
                    SearchLanguage = Language.en,
                    PageSize = 10,
                    Page = 1
                };

                var response = await client.DoQueryAsync(request);
            }
```
.net version 4.5.1

**Comment by bl8** [comment]
It seems that the server thinks there is something wrong with your request. The query itself is fine, so maybe related with authentication. Are you using the password provided after you registered on EUR-Lex to use their web service ?
See:
https://eur-lex.europa.eu/content/help/faq/reuse-contents-eurlex-details.html

The server send more details about the problem, but after your previous report, I realized this is not handled correctly, so there probably isn't more info in the FaultException. I'm working to fix this.

In the meantime, you can log the whole response from the server, it should give you more details about the problem.
You can see how to do this with a response handler in the "Console" sample:
https://github.com/EULexNET/EULex.NET/blob/master/samples/Console/Program.cs#L46

**Comment by mirhat** [comment]
I have got to this message 

> env:Senderwsse:FailedAuthenticationFailed to assert identity with UsernameToken. to assert identity with UsernameToken.

Request xml is as follows

```
<?xml version="1.0" encoding="UTF-8"?>
<q1:Envelope xmlns:q1="http://www.w3.org/2003/05/soap-envelope">
    <q1:Header>
        <wsse:Security xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" xmlns:d1p1="http://www.w3.org/2003/05/soap-envelope" d1p1:mustUnderstand="1">
            <wsse:UsernameToken xmlns:d2p1="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" d2p1:Id="_UT84775c54e2e64ebfbc43bbed39965c60">
                <wsse:Username>MyUsername</wsse:Username>
                <wsse:Password Type="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-username-token-profile-1.0#PasswordText">MyPassword</wsse:Password>
            </wsse:UsernameToken>
        </wsse:Security>
    </q1:Header>
    <q1:Body>
        <q1:searchRequest xmlns:q1="http://eur-lex.europa.eu/search">
            <q1:expertQuery>food</q1:expertQuery>
            <q1:page>1</q1:page>
            <q1:pageSize>2</q1:pageSize>
            <q1:searchLanguage>en</q1:searchLanguage>
        </q1:searchRequest>
    </q1:Body>
</q1:Envelope>
```

**Comment by mirhat** [comment]
It was resolved by registering to webservice :/

**Comment by bl8** [comment]
Thanks for the update, and I'm happy that it works for you now.

So I'm closing this issue.
